In [1]:
import pandas as pd
import numpy as np

In [168]:
###Loading the features of test data set
data2=pd.read_csv("test_set_features.csv")

In [98]:
###Loading the features of train data set
data1=pd.read_csv("training_set_features.csv")
data1.describe()

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,health_worker,health_insurance,opinion_xyz_vacc_effective,opinion_xyz_risk,opinion_xyz_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,household_adults,household_children
count,26707.000000,26615.000000,26591.000000,26636.000000,26499.000000,26688.000000,26665.000000,26620.00000,26625.000000,26579.000000,...,25903.000000,14433.00000,26316.000000,26319.000000,26312.000000,26245.000000,26193.000000,26170.000000,26458.000000,26458.000000
mean,13353.000000,1.618486,1.262532,0.048844,0.725612,0.068982,0.825614,0.35864,0.337315,0.677264,...,0.111918,0.87972,3.850623,2.342566,2.357670,4.025986,2.719162,2.118112,0.886499,0.534583
std,7709.791156,0.910311,0.618149,0.215545,0.446214,0.253429,0.379448,0.47961,0.472802,0.467531,...,0.315271,0.32530,1.007436,1.285539,1.362766,1.086565,1.385055,1.332950,0.753422,0.928173
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,6676.500000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,...,0.000000,1.00000,3.000000,1.000000,1.000000,4.000000,2.000000,1.000000,0.000000,0.000000
50%,13353.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.00000,0.000000,1.000000,...,0.000000,1.00000,4.000000,2.000000,2.000000,4.000000,2.000000,2.000000,1.000000,0.000000
75%,20029.500000,2.000000,2.000000,0.000000,1.000000,0.000000,1.000000,1.00000,1.000000,1.000000,...,0.000000,1.00000,5.000000,4.000000,4.000000,5.000000,4.000000,4.000000,1.000000,1.000000
max,26706.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,...,1.000000,1.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,3.000000,3.000000

In [99]:
### Loading target values of training dataset
out=pd.read_csv("training_set_labels.csv")
out1=out[['xyz_vaccine']]
out2=out[['seasonal_vaccine']]
out.describe()

       respondent_id   xyz_vaccine  seasonal_vaccine
count   26707.000000  26707.000000      26707.000000
mean    13353.000000      0.212454          0.465608
std      7709.791156      0.409052          0.498825
min         0.000000      0.000000          0.000000
25%      6676.500000      0.000000          0.000000
50%     13353.000000      0.000000          0.000000
75%     20029.500000      0.000000          1.000000
max     26706.000000      1.000000          1.000000

In [100]:
### Converting categorial data into numerical data for training dataset
data1['age_group'].replace(['55 - 64 Years', '35 - 44 Years', '18 - 34 Years', '65+ Years',
       '45 - 54 Years'],
                        [4,2,1,5,3], inplace=True)
data1['education'].replace(['< 12 Years', '12 Years', 'College Graduate', 'Some College'],
                        [1,2,4,3], inplace=True)
data1['race'].replace(['White', 'Black', 'Other or Multiple', 'Hispanic'],
                        [1,2,3,4], inplace=True)
data1['sex'].replace(['Female', 'Male'],
                        [0,1], inplace=True)
data1['income_poverty'].replace(['Below Poverty', '<= $75,000, Above Poverty', '> $75,000'],
                        [0,1,2], inplace=True)
data1['marital_status'].replace(['Not Married', 'Married'],
                        [0,1], inplace=True)
data1['rent_or_own'].replace(['Own', 'Rent'],
                        [1,0], inplace=True)
data1['employment_status'].replace(['Not in Labor Force', 'Employed', 'Unemployed'],
                        [1,2,0], inplace=True)
hhs_map=data1['hhs_geo_region'].value_counts().to_dict()
data1['hhs_geo_region']=data1['hhs_geo_region'].map(hhs_map)
data1['census_msa'].replace(['Non-MSA', 'MSA, Not Principle  City', 'MSA, Principle City'],
                        [0,1,2], inplace=True)
ei_map=data1['employment_industry'].value_counts().to_dict()
data1['employment_industry']=data1['employment_industry'].map(ei_map)
eo_map=data1['employment_occupation'].value_counts().to_dict()
data1['employment_occupation']=data1['employment_occupation'].map(eo_map)

In [170]:
### Converting categorial data into numerical data for test dataset
data2['age_group'].replace(['55 - 64 Years', '35 - 44 Years', '18 - 34 Years', '65+ Years',
       '45 - 54 Years'],
                        [4,2,1,5,3], inplace=True)
data2['education'].replace(['< 12 Years', '12 Years', 'College Graduate', 'Some College'],
                        [1,2,4,3], inplace=True)
data2['race'].replace(['White', 'Black', 'Other or Multiple', 'Hispanic'],
                        [1,2,3,4], inplace=True)
data2['sex'].replace(['Female', 'Male'],
                        [0,1], inplace=True)
data2['income_poverty'].replace(['Below Poverty', '<= $75,000, Above Poverty', '> $75,000'],
                        [0,1,2], inplace=True)
data2['marital_status'].replace(['Not Married', 'Married'],
                        [0,1], inplace=True)
data2['rent_or_own'].replace(['Own', 'Rent'],
                        [1,0], inplace=True)
data2['employment_status'].replace(['Not in Labor Force', 'Employed', 'Unemployed'],
                        [1,2,0], inplace=True)
hhs_map2=data2['hhs_geo_region'].value_counts().to_dict()
data2['hhs_geo_region']=data2['hhs_geo_region'].map(hhs_map2)
data2['census_msa'].replace(['Non-MSA', 'MSA, Not Principle  City', 'MSA, Principle City'],
                        [0,1,2], inplace=True)
ei_map=data2['employment_industry'].value_counts().to_dict()
data2['employment_industry']=data2['employment_industry'].map(ei_map)
eo_map=data2['employment_occupation'].value_counts().to_dict()
data2['employment_occupation']=data2['employment_occupation'].map(eo_map)

In [101]:
### Filling Nan values with mode 
from sklearn.impute import SimpleImputer 
for i in range(36):
    X = data1.iloc[:, i].values.reshape(-1, 1) 
      
    # To calculate mean use imputer class 
    imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent') 
    imputer = imputer.fit(X) 
      
    X = imputer.transform(X) 
    data1.iloc[:, i]=X

In [171]:
from sklearn.impute import SimpleImputer 
for i in range(36):
    X = data2.iloc[:, i].values.reshape(-1, 1) 
      
    # To calculate mean use imputer class 
    imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent') 
    imputer = imputer.fit(X) 
      
    X = imputer.transform(X) 
    data2.iloc[:, i]=X

In [77]:
data1.isnull().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
income_poverty                 0
marital_status                 0
rent_or_own                    0
employment_status              0
hhs_geo_region                 0
census_msa                     0
household_adults               0
household_children             0
employment_industry            0
employment_occupation          0
dtype: int64

In [172]:
data2.isnull().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
age_group                      0
education                      0
race                           0
sex                            0
income_poverty                 0
marital_status                 0
rent_or_own                    0
employment_status              0
hhs_geo_region                 0
census_msa                     0
household_adults               0
household_children             0
employment_industry            0
employment_occupation          0
dtype: int64

In [103]:
### Using bobustScaler for scaling
from sklearn.preprocessing import RobustScaler
transformer = RobustScaler().fit(data1)
da1=transformer.transform(data1)

In [104]:
df = pd.DataFrame(da1)

In [105]:
df

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,-1.000000,-1.0,-1.0,0.0,-1.0,0.0,-1.0,0.0,1.0,0.0,...,-1.0,-1.0,0.0,-1.0,0.000000,-0.5,-1.0,0.0,0.000000,0.000000
1,-0.999925,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-1.0,-1.0,-1.0,0.0,-0.012720,0.0,-1.0,0.0,-0.928016,-1.000000
2,-0.999850,-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0,...,0.0,-1.0,0.0,0.0,0.237769,0.0,1.0,0.0,-1.261349,0.000000
3,-0.999775,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-0.764188,0.5,-1.0,0.0,0.000000,0.000000
4,-0.999700,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.237769,0.0,0.0,0.0,-0.430610,-0.729885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,0.999700,0.0,-1.0,0.0,0.0,0.0,-1.0,0.0,1.0,-1.0,...,0.0,-1.0,0.0,-1.0,0.237769,-0.5,-1.0,0.0,0.000000,0.000000
26703,0.999775,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,...,0.0,-1.0,-1.0,0.0,1.407045,0.5,0.0,0.0,0.000000,-0.762931
26704,0.999850,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,-1.0,0.0,0.0,1.407045,0.0,-1.0,0.0,0.000000,0.000000
26705,0.999925,-1.0,0.0,0.0,-1.0,0.0,-1.0,0.0,0.0,0.0,...,0.0,0.0,-1.0,0.0,-0.764188,-0.5,0.0,0.0,0.000000,-2.129310
26706,1.000000,-2.0,-1.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0,...,0.0,0.0,0.0,-1.0,-0.602740,0.5,0.0,0.0,0.000000,0.000000

In [155]:
df.drop(df.columns[[0]], axis=1, inplace=True)

In [156]:
df

,1,2,3,4,5,6,7,8,9,10,...,26,27,28,29,30,31,32,33,34,35
0,-1.0,-1.0,0.0,-1.0,0.0,-1.0,0.0,1.0,0.0,0.0,...,-1.0,-1.0,0.0,-1.0,0.000000,-0.5,-1.0,0.0,0.000000,0.000000
1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,-1.0,-1.0,-1.0,0.0,-0.012720,0.0,-1.0,0.0,-0.928016,-1.000000
2,-1.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,...,0.0,-1.0,0.0,0.0,0.237769,0.0,1.0,0.0,-1.261349,0.000000
3,-1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.0,0.0,...,-1.0,-1.0,-1.0,-1.0,-0.764188,0.5,-1.0,0.0,0.000000,0.000000
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.237769,0.0,0.0,0.0,-0.430610,-0.729885
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,0.0,-1.0,0.0,0.0,0.0,-1.0,0.0,1.0,-1.0,0.0,...,0.0,-1.0,0.0,-1.0,0.237769,-0.5,-1.0,0.0,0.000000,0.000000
26703,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,...,0.0,-1.0,-1.0,0.0,1.407045,0.5,0.0,0.0,0.000000,-0.762931
26704,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,-1.0,0.0,0.0,1.407045,0.0,-1.0,0.0,0.000000,0.000000
26705,-1.0,0.0,0.0,-1.0,0.0,-1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,-1.0,0.0,-0.764188,-0.5,0.0,0.0,0.000000,-2.129310
26706,-2.0,-1.0,0.0,0.0,0.0,-1.0,0.0,0.0,-1.0,0.0,...,0.0,0.0,0.0,-1.0,-0.602740,0.5,0.0,0.0,0.000000,0.000000

In [173]:
from sklearn.preprocessing import RobustScaler
transformer = RobustScaler().fit(data2)
da2=transformer.transform(data2)
df2 = pd.DataFrame(da2)

In [174]:
df2.drop(df2.columns[[0]], axis=1, inplace=True)

In [181]:
from sklearn.model_selection import train_test_split
X_train=df
X_test=df2
y_train1=out1
y_train2=out2

In [182]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
clf = LogisticRegression(solver="liblinear", random_state=0).fit(X_train,y_train1)
roc_auc_score(y_train1, clf.predict_proba(X_train)[:, 1])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8311697309133083

In [183]:
clf2 = LogisticRegression(solver="liblinear", random_state=0).fit(X_train,y_train2)
roc_auc_score(y_train2, clf2.predict_proba(X_train)[:, 1])

/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8482731729657899

In [184]:
data3=pd.read_csv("submission_format.csv")

In [185]:
data3['h1n1_vaccine']=clf.predict_proba(X_test)[:, 1]
data3['seasonal_vaccine']=clf2.predict_proba(X_test)[:, 1]

In [186]:
data3.describe()

       respondent_id  h1n1_vaccine  seasonal_vaccine
count   26708.000000  26708.000000      26708.000000
mean    40060.500000      0.212860          0.466778
std      7710.079831      0.217261          0.298382
min     26707.000000      0.002877          0.004308
25%     33383.750000      0.063293          0.193552
50%     40060.500000      0.122018          0.432111
75%     46737.250000      0.287418          0.747322
max     53414.000000      0.969156          0.988335

In [187]:
data3.to_csv('jayant_datahack.csv',index=False)